### ISSUE TITLE
Internationalization and other UI settings

### ISSUE THREAD

**Issue by idanstark42** [FirstLegoLeagueIL/architecture#4]
Settings that should be included are:
1. styles.css route and styles.js route
1. internationalization route - maybe the translation for a certain word be requested over HTTP, and the change of language should be notified over an Mhub message?

**Comment by idanstark42** [comment]
Possible solution:
1. The routes will be included as environment variables ONLY IF the module adds `ui` to its `require` field.
2. There will be no internationlization route, and this can be solved in one of 2 ways:
2.1. The Javascript way. This means that the javascript file for the styles will contain a JSON object `LANGUAGE` that can be used throughout the system, and a simple module that inserts into every `<div translate="property-name"></div>` the correct translated property value.
2.2. The CSS way. This means that the CSS file will contain a series of cascades that look like this:
```css
[translate="property-name"]:after { content: "translated property value"; }
```
And so, every `<div translate="property-name"></div>` will be inserted with the givven property value. The advantage of this option is its imidiate action, not having to wait for the JS replacment to run, CSS is acted upon initial drawing of the page.

In any of the options for the internationalization, I reccomend having another route for recieving a specific word, and that the internationalization will need to be added to the `require` field, so that we have `translated ui` and `ui` as choices.

This all I think should be kept in a special UI module just for the sharing of these files

**Comment by 2roy999** [comment]
1. Settings should not include styles.css and styles.js. The official modules would have the same style by our design of the system, and non-official module is entitled to choose whatever style he wants.

2. i18n - The use of i18n itself should be used with some external library relevant suitable for the framework used by module (if module even have ui). So our only question is how to change the langunage, I we should start with some file with the translation. Which we would change on setup (Iater we might add an external tool to create a translated file). The key point is that we don't want it to change in real-time.

**Comment by idanstark42** [comment]
1. UX speaking, we should create a uniform styling for the system.
2. Creating a file on setup is good. How will the modules obtain it?

**Comment by 2roy999** [comment]
Ok, there are two issues here:
1. There will standard ui but not part of MS
2. We will use i18n framework in New modules but we would create the full integration later with luancher.
