### ISSUE TITLE
How does the Launcher know the initial values of the configuration fields?

### ISSUE THREAD

**Issue by idanstark42** [FirstLegoLeagueIL/architecture#7]
The `module.yml` cannot contain the values, because they change at runtime, so we need to find another way of communicating them.

If there's a web module which manages the configuration on the client side, and we do the following actions, what will happen:
1. Open a browser with the module client
2. Change a configuration from the Launcher
3. Open another browser with that page
4. Change another field in the configuration

Sometimes the configuration that is created in this situation on the second browser will not make any sense

**Comment by idanstark42** [comment]
Didn't we said it's not the launcher's resistibility to save the configuration? If the launcher is providing a saving area for configuration, it should be said in the MS

**Comment by 2roy999** [comment]
You're right we did said that in the arch meeting, but looking on the process again, it's seems weird. So I want to change it. (I think we did it because of local configurations that won't be configured via the launcher

**Comment by idanstark42** [comment]
OK. Then I'll update the developer tutorial to reflect that, and we should update the MS accordingly. @alanggreen @yosikarl @taltaub22 Just want to make sure no one objects to the Launcher holding the configuration in order to create a Single Point of Truth for it, in case of clientside-only services.

**Comment by 2roy999** [comment]
See pr #12 and #9
